server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: localhost
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/swagger-ui.html, /v3/api-docs/**, /swagger-ui/**,/users/**,/roles/**
            #- Path=/users/**
          filters:
            - RewritePath=/USERSERVICE/(?<segment>.*), /$\\{segment}
      discovery:
        locator:
          enabled: true
        #lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: "*"


